final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '1',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '2',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '3',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '4',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '5',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '6',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '7',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '8',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '9',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '10',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '11',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '12',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '13',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '14',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '15',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '16',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '17',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '18',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '19',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '20',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '21',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '22',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '23',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '24',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '25',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '26',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '27',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '28',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '29',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '30',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '31',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '32',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
];

final cart = [
  {
    'id': '32',
    'title': 'Men\'s Nike shoes',
    'price': 44.52,
    'imageURL': 'assets/images/shoes-5.jpg',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
];
